// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("SharePointAppWeb")]
[assembly: AssemblyProductAttribute("FSharpReactJS")]
[assembly: AssemblyDescriptionAttribute("Project has no summmary; update build.fsx")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
